### ISSUE TITLE
Generate report without jQuery

### ISSUE THREAD

**Issue by nbhattarai** [jls/nightwatch-html-reporter#17]
Is it possible to generate static html without jquery?
I wanted to generate HTML report as a last step of jenkins job. Currently it only attaches  collapsed view.

Actual:
![screen shot 2015-05-05 at 8 16 08 am](https://cloud.githubusercontent.com/assets/8496184/7475880/0d852646-f2ff-11e4-89f3-40295c02f0cc.png)

Expected:
![screen shot 2015-05-05 at 8 17 55 am](https://cloud.githubusercontent.com/assets/8496184/7475923/43e465a8-f2ff-11e4-8377-3816a34b9984.png)

**Comment by jls** [comment]
Sure thing.  That's because we use the stylesheet to init the dom elements collapsed and then use jQuery to open them when you click.  But what we can do instead is init the styles as showing and use jQuery to collapse the elements.  That way if jQuery isn't included then you see the expanded results.

Let me look into it a little more and I'll try and get something out in the next day or so.

**Comment by nbhattarai** [comment]
Thanks a lot.

**Comment by jls** [comment]
Fixed in 1.0.2.  I've changed the styles so that all elements are initially visible then if jQuery is included it will collapse them, otherwise all will be visible.

Thanks again!
