### ISSUE TITLE
Report not working when running parallel browsers

### ISSUE THREAD

**Issue by louiscbotha** [jls/nightwatch-html-reporter#21]
When running tests with nightwatch using multiple browsers simultaneously, the exported report doesn't combine all the output reports into one. Currently only one of the reports gets provided in html.

There should be a way that this nightwatch-html-reporter automatically fetches all reports for each of these browsers and combines it into one report.

**Comment by louiscbotha** [comment]
Hmm seems like I was wrong.

**Comment by Zeboch** [comment]
How do you manage to get multiple reports ? I'm on the same dead end : I'm running tests on parallel browsers and only one report is generated.

**Comment by jls** [comment]
Hello,
Are you running the reporter from the command line or using the reporter option in nightwatch/global.js?
One other question is how are you starting the parallel tests? In the nightwatch docs it looks like if you run tests in parallel using the same browser the reports are overwritten since the browser name is the same.

On Wed, Apr 13, 2016 at 4:36 AM, Zeboch <notifications@github.com> wrote:
How do you manage to get multiple reports ? I'm on the same dead end : I'm running tests on parallel browsers and only one report is generated.

**Comment by Zeboch** [comment]
I'm using reporter option. But I find a workaround : this is ma html-reporter.js file

````
var HtmlReporter = require('nightwatch-html-reporter');

/* Same options as when using the built in nightwatch reporter option */
var reporter = new HtmlReporter({
	openBrowser: false,
	reportsDirectory: 'src/e2e/javascript/reports/',
	reportFilename: 'report' + '_' + process.env.__NIGHTWATCH_ENV + '.html',
	themeName: 'outlook'
});

module.exports = {
	write : function(results, options, done) {
		reporter.fn(results, done);
	}
};
```` 

Meaning it's ok if reporteFilename is different for every report. And if you run tests using same browser in parallel, I suggest to add a timestamp ;)

**Comment by jls** [comment]
Perfect thank you!  If you don't mind I'll add a section to the readme that outlines your solution in case others try and do the same thing.

**Comment by Zeboch** [comment]
I think it's not a perfect solution but if it helps, no problemo ;)

**Comment by nestoru** [comment]
@jls Thanks for this package. 

@louiscbotha I think you closed the issue prematurely. If multiple tests are run in parallel in a multicore machine the issue is evident.

Given that NighWatch does create individual report JUnit XML files per browser and test file name, I believe it makes sense to support the creation of a single html file. 

I created https://github.com/nestoru/nightwatch-lean-e2e, partly to fundament the need for keeping the results in just one file. I think that having just one report.html containing the result of all tests is a real need. 

For now something like the below can be used to catch the results in ansi and html as explained in the nightwatch-lean-e2e project. Note the usage of the ENV VAR $APP_VERSION, which allows to keep the history of each e2e run per app deployed version:

`RPT_DIR=reports/$APP_VERSION; mkdir -p "$RPT_DIR"; nightwatch --config nightwatch.conf.js | tee  "$RPT_DIR/console-report.ansi"; cat "$RPT_DIR/console-report.ansi" |  ansi-to-html -n > "$RPT_DIR/console-report.html"`
