### ISSUE TITLE
Missing successful assertions?

### ISSUE THREAD

**Issue by wintermute77** [jls/nightwatch-html-reporter#25]
I'm using grunt-nightwatch 0.5.2, with nightwatch 0.8.14.

The XML file generated by my tests doesn't seem to include any information relating to successful assertions, only failures. Looking at the jUnit XML schema, this seems intentional.

However, when I run:
`nightwatch-html-reporter -d /path/to/test/reports`
The HTML file also doesn't include any entries relating to successful assertions - there is no `.package.success` div.

What am I not understanding here? Where does nightwatch-html-reporter get information about successful assertions from? Should it be in the XML? It's not, and I'd expect it to be, but the schema seems to suggest otherwise.

**Comment by jls** [comment]
If you run the reporter from the command line then it should get all of it's information from the XML files.  The XML files should have information about all assertions not just the failures.  You can see an example of what we expect in https://github.com/jls/nightwatch-html-reporter/blob/master/test/mockdata/xmlreport.xml.  

That was also generated with nightwatch version 0.7.x though so in 0.8 that may have changed.  They tend to change the reporters and the format of those generated XML files pretty often without a minor version bump.

**Comment by jls** [comment]
Just ran a quick test and it looks like successful assertions are not in the XML file but they are still given to the reporter if you specify it in your globals.js (https://github.com/jls/nightwatch-html-reporter#using-the-reporter-with-the-built-in-nightwatch-reporter)

If any of the assertions in a test or package have failed then we mark the entire package as failed for display purposes so unless all assertions in your tests passed you would see a .package.error instead of a .package.success.

I'm going to close this because if successful assertions are not in the XML there is nothing I can look at to get them.  But if you have other questions or suggestions for changes then please re-open!

**Comment by wintermute77** [comment]
Hi - thanks for the reply! This did help resolve the issue - I can generate the report as you suggest, via the inbuilt reporter, i.e:
grunt nightwatch:chrome --tag brochure-form --reporter test/html-reporter.js

This does result in successful assertions being written to the HTML file.

Many thanks for your help.

**Comment by jls** [comment]
No problem, glad to hear it!
