### ISSUE TITLE
Create single report file when we execute tests in parallel

### ISSUE THREAD

**Issue by shripadbothaleAvalara** [jls/nightwatch-html-reporter#47]
When we run tests in parallel we may get report in two ways

1. When **uniqueFilename = true** then we will get different report for every parallel execution (like i ran 20 js file then it will generate 20 html reports)
2. When **uniqueFilename = false** then we will have only one file containing result for last executed test.js 

Can we have a flag to have single file even when we run tests in parallel (we executed total 20 tests.js and able to generate one html report containing result for all 20 tests.js

**Comment by jls** [comment]
Hello!  Unfortunately that has to do with how we receive the report object from Nightwatch.  When you run in parallel then Nightwatch calls the reporter for each individual test and as far as I can tell we don't get an indication that it's a parallel run.  Since we don't know it's a parallel run we don't know that we should combine any of the test reports.

What you might be able to try though is look in your Nightwatch reports directory and if there is an individual XML file for each of the tests ran in parallel then you can use those to generate a single report for all of the tests.  

See here for instructions on how to run from the command line.  Let me know if that works for you!
https://github.com/jls/nightwatch-html-reporter#cli-usage
