### ISSUE TITLE
Customise Night watch report

### ISSUE THREAD

**Issue by DeviKuppili** [jls/nightwatch-html-reporter#57]
Can anyone guide or share code to customise the nightwatch report generated from XML in the form of tabular html report having the columns as Test suite,Test cases ,Assertions and execution status adding one row for each test suite.

**Comment by jls** [comment]
Hello @DeviKuppili!  The best way to get started with a custom theme would be to [look at the report.pug](https://github.com/jls/nightwatch-html-reporter/blob/master/lib/themes/default/report.pug) file in the default theme.  That will show you all of the information available and let you organize it however you want. 

Since we just use Pug to generate the HTML, [their docs would be a good place](https://pugjs.org/api/getting-started.html) to see what's possible.
